### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/YjMonitor#1]
1.设置范围1-5000，会出现连接不上，是不是因为大量访问被封IP？这样通过拨号可以解决？貌似不可以。。
2.只是发送结果到目标房间是吗？不会参与抽奖。
3.该监控是否只检测两种礼物（测试几秒钟就看到两种输出结果）。
4.测试了一下默认设置，是随机监控500个房间吗？
5.live-tools（或者bili2.0）有获取弹幕结果来进行参与吗？没有的话只能自己另外想办法写一个参与？（苦手）

**Comment by yjqiang** [comment]
5000超过python负载
不抽奖
仅风暴和舰长/提督
按照热度排序
user.toml里面最后一行就是，已经对接

**Comment by rabbit2rabbit** [comment]
1.非常感谢，能告诉我这个对接弹幕的源码在哪个部分吗？我想学习下。
2.其次，假如要多台机器开监控，避免重复，是不是应该每台的STAR END都错开，例如"1,500""501,1000"……"20001,20500"这样子是吗？STAR END就是热度的排序对吗
3.刚启动的输出2行数字“XX”XXXX"是"连接XXXX个直播间中的XX个"的意思吗？

**Comment by yjqiang** [comment]
搜索Yj就知道了，基本在connect.py和biliCilent.py里面
对的，设计目的就是协同监控
xx号弹幕姬是指标号，从0开始的；（xxxx）是房间监听号

**Comment by rabbit2rabbit** [comment]
嗯好的~感激。
突然发现live-tools的storm悄咪咪的移除了（小声BB）

**Comment by yjqiang** [comment]
没有什么用，我写在了rafflehandler里面，但是就尝试一次，你可以自己弄，但是涉及利益问题，不要公开
