### ISSUE TITLE
近两天被封直播弹幕多了

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/YjMonitor#10]
近期有许多帐号都被封禁直播区的弹幕，提示：“发送失败，您的账号可能存在风险，暂时无法发送消息，请确保账号资料属实并绑定真实手机号码”
即使是真人帐号使用也还是会被封禁，小号几乎都阵亡了

**Comment by rabbit2rabbit** [comment]
![image](https://user-images.githubusercontent.com/42423154/48400792-4f6aa300-e762-11e8-8338-373ebfff5441.png)
咨询客服

**Comment by yjqiang** [comment]
是的 其他用户也有反馈

**Comment by yjqiang** [comment]
在考虑做服务器部分  取代弹幕

**Comment by rabbit2rabbit** [comment]
理解不了什么想法，怎么个思路，能说说吗

**Comment by yjqiang** [comment]
向服务器发送信息 然后get服务器的合计信息

**Comment by yjqiang** [comment]
不过不打算websocket  用户多了的话 性能可能有问题

**Comment by rabbit2rabbit** [comment]
定时GET合计信息？一瞬间单用户领取或许不会403，但是bili2.0的话肯定会403

**Comment by yjqiang** [comment]
嗯  应该不会的  2.0有一个superuser专门干脏活 只由这个人获取 其他人分享这个结果

**Comment by yjqiang** [comment]
另外 我怀疑可能b站封是因为尝试过多吧……  反正你看看最新版  试试如何吧

**Comment by rabbit2rabbit** [comment]
主要是2.0没有对接新监控。。我主要用在2.0上。（催一下2.0的yjmoniter）

每次都1秒内尝试5-6次的弹幕实在是有点频率过高，根据客服的回答也是这个样子，即使是热度不高的监控（几十分钟发一次弹幕的）也会被封禁

**Comment by yjqiang** [comment]
最新版早就处理了呀 控制基本最多1.5s尝试一次

**Comment by yjqiang** [comment]
最近没再发生了  没有类似反馈  猜测可能是之前关键词的屏蔽导致触发
