### ISSUE TITLE
重复弹幕

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/YjMonitor#11]
![image](https://user-images.githubusercontent.com/42423154/48401148-4dedaa80-e763-11e8-9882-de42aaf51c7f.png)

**Comment by yjqiang** [comment]
不清楚原因 因为理论上这个东西发送之后不再重试

**Comment by yjqiang** [comment]
@rabbit2rabbit 最新版启用了偏僻字进行规避关键字  基本不会出现了

**Comment by yjqiang** [comment]
duplicated #9
