### ISSUE TITLE
关于分发的房间列表的疑问

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/YjMonitor#12]
今天通过对比，发现有些房间还是没有监控到。
看到是get了lc4t的列表，不清楚lc4t是怎么一个获取房间排列的方法，是否仅查看开播房间？
因为我查看了一些有舰长的房间id并没有出现在lc4t的列表中。
想看看lc4t的房间id能不能再改进一下这样子，因为只有6000个不到的房间id

**Comment by yjqiang** [comment]
房间肯定会至少6000个  分发策略里面写的

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili_utils/tree/master/fetch_roomids/refresh_rooms_hub

**Comment by yjqiang** [comment]
正在想办法扩充到10k这样  但是需要补足房间作填充  还在跑抓取的代码  b站限制0.3秒10个请求……  跑不快

**Comment by yjqiang** [comment]
> 今天通过对比，发现有些房间还是没有监控到。
> 看到是get了lc4t的列表，不清楚lc4t是怎么一个获取房间排列的方法，是否仅查看开播房间？
> 因为我查看了一些有舰长的房间id并没有出现在lc4t的列表中。
> 想看看lc4t的房间id能不能再改进一下这样子，因为只有6000个不到的房间id
> 

你看一下代码  确认一下缺失的房间是开播的还是未开播的  开播的话说明server的过滤可能比较严格  未开播可能我的固定roomid有问题  需要重跑

**Comment by rabbit2rabbit** [comment]
我刚手动测试了一些，1/13是没有监控到的房间数据。是开播状态的

**Comment by rabbit2rabbit** [comment]
用bili-live tool看时间戳了，刚刚的10分钟漏了13个房间的舰长

**Comment by yjqiang** [comment]
> 我刚手动测试了一些，1/13是没有监控到的房间数据。是开播状态的

我是根据观看人数（热度）限制的 目前好像100？  你看看热度多少；以及20分钟间隔刷新  所以可能会出现没来得及更新  这是无法解决的

**Comment by rabbit2rabbit** [comment]
有一个开播9小时的房间，排除20分钟刷新问题，有舰长后是6000人气，舰长前人气是多少就无从得知了（2181关注的）

**Comment by yjqiang** [comment]
目前我的措施是动态刷新得到的房间+默认按照关注人数得到的静态房间号
其中动态刷新间隔为20分钟  优先级靠前

**Comment by yjqiang** [comment]
> 有一个开播9小时的房间，排除20分钟刷新问题，有舰长后是6000人气，舰长前人气是多少就无从得知了（2181关注的）

其实还有一种可能  监控的服务器掉线了……  所以建议直接调用lc4t的api确认

**Comment by rabbit2rabbit** [comment]
lc4t监控漏掉的比较少，可能是1/13的数据，live-tool漏掉的太多了

**Comment by rabbit2rabbit** [comment]
刚一个171万关注的房间也漏掉了，补足的房间ID.toml中有这个房间号，但是并没有监控到

**Comment by yjqiang** [comment]
> lc4t监控漏掉的比较少，可能是1/13的数据，live-tool漏掉的太多了

live-tool?什么意思？

**Comment by yjqiang** [comment]
> 刚一个171万关注的房间也漏掉了，补足的房间ID.toml中有这个房间号，但是并没有监控到

`f'http://room.lc4t.cn:8000/is_in/{room_id}'`判断是否纳入监控范围了

**Comment by rabbit2rabbit** [comment]
bili-live -tool……我在用bili-live-tool看着获取到的舰长id，根据我在别的地方看到的舰长房间id做对比，lc4t的api有这个房间号，但是在实际使用bili-live-tool的时候是没有获取到该房间id

**Comment by yjqiang** [comment]
当前有个1200-1600和5200-5600的掉线了  没办法

**Comment by yjqiang** [comment]
> bili-live -tool……我在用bili-live-tool看着获取到的舰长id，根据我在别的地方看到的舰长房间id做对比，lc4t的api有这个房间号，但是在实际使用bili-live-tool的时候是没有获取到该房间id

如果lc4t有的话  基本可能就是有人掉线了……

**Comment by rabbit2rabbit** [comment]
那或许是这个原因导致实际使用bili-live-tool的时候漏掉许多。
然后我下午的时候手动对比api获取的房间，漏了一个。不知道那里是怎么个情况

**Comment by yjqiang** [comment]
> 那或许是这个原因导致实际使用bili-live-tool的时候漏掉许多。
> 然后我下午的时候手动对比api获取的房间，漏了一个。不知道那里是怎么个情况

你把他人额外的相关api发我邮箱吧  yjqiang1@outlook.com    我看看有时间能不能写一个对比的东西    再提高精度

**Comment by rabbit2rabbit** [comment]
emmmm我只是在某人的软件看log对比的，没有api,也不会接上别人的监控

**Comment by yjqiang** [comment]
> emmmm我只是在某人的软件看log对比的，没有api,也不会接上别人的监控

那你有时间继续观察吧  主要是查看lc4t的直接api即可  分发过程造成的误差暂时不考虑
之后反馈过来  我看看能不能接着调节

**Comment by yjqiang** [comment]
目前我没有什么大的改动计划了  在做的就是调参和爬静态roomid

**Comment by rabbit2rabbit** [comment]
![image](https://user-images.githubusercontent.com/42423154/50342582-94060d00-055e-11e9-8f2c-e860b6f64bd9.png)
手动一个小时对比，这些都是lc4t的api里面没有监控到的房间信息，看看参考

**Comment by yjqiang** [comment]
有时候不开播好像也有人气吧……  会有么

**Comment by rabbit2rabbit** [comment]
这些全部都是开播的状态

**Comment by yjqiang** [comment]
> 这些全部都是开播的状态

可能是没有监控到吧……有api可以查看开播时间的

**Comment by yjqiang** [comment]
主要是这样  我爬取的时候  是调用了2个api  各自尝试2次  然后取合集……所以个人觉得不应该

**Comment by rabbit2rabbit** [comment]
监控这个一般都是取多的比较好吧。
应该不取交集，两个api合并之后剔除重复这样或许可以，就是不清楚两个api能不能监控到这么多

**Comment by yjqiang** [comment]
> 监控这个一般都是取多的比较好吧。
> 应该不取交集，两个api合并之后剔除重复这样或许可以，就是不清楚两个api能不能监控到这么多

这样的话  判定遗漏判定需要满足  开播时间较短、search api诡异没收录、人气挺高
