### ISSUE TITLE
影响命中率因素与已有的一些措施

### ISSUE THREAD

**Issue by yjqiang** [yjqiang/YjMonitor#13]
1. 分发lc4t服务器20分钟间隔的刷新率，可能导致房间没有及时获取到

1. 房间的选取是开播房间（按照热度排序）+ 未开播的房间（按照关注度排序），可能具体的阈值控制要调整

**Comment by yjqiang** [comment]
#12

**Comment by yjqiang** [comment]
目前晚高峰可以在95%左右了，基本需要大改了，目前方案改到头了

**Comment by yjqiang** [comment]
精确的统计之后7k房间覆盖率为93.5-94%。当前使用策略还是一代策略，是动态+静态房间，其中动态优先级最高，按人气排序；静态房间优先级低，按舰队数目排序。

**Comment by yjqiang** [comment]
2代还在构思中，初步打算把动态和静态的分离出来，分成两个部分去监控，运行在不同房间里面。

**Comment by yjqiang** [comment]
监控可以使用 https://live.bilibili.com/p/eden/rank#/childnav/vitality/0 作为房间的又一个来源。但是这个比较少，估计撑死混合起来200.

**Comment by yjqiang** [comment]
> 2代还在构思中，初步打算把动态和静态的分离出来，分成两个部分去监

不需要了，https://github.com/yjqiang/YjMonitor/commit/22e9f696235c59019915c0c14d80285f2c946d4f 可以休眠与唤醒，不需要管多余房间

**Comment by yjqiang** [comment]
加入弹幕监控（推送就认定是潜在热门用户） 感谢https://github.com/lzghzr

**Comment by yjqiang** [comment]
加入实时刷新（几乎实时），感谢 https://github.com/Dawnnnnnn

**Comment by yjqiang** [comment]
由于实时刷新api是2b的，加入poll策略缓和，覆盖率应该稳定在99%+

**Comment by yjqiang** [comment]
覆盖率达到99.5

**Comment by yjqiang** [comment]
基本符合个人使用要求了

**Comment by Billyzou0741326** [comment]
代码实在有点难读2333 所以想了下还是直接问吧

这种堪称恐怖的覆盖率采用的全部是WS弹幕协议监听的吗？感觉这样的话要处理相当大量的数据...
不过房间选取的这个API <http://api.live.bilibili.com/room/v1/Area/getListByAreaID?areaId=0&sort=online&pageSize=200&page=1> 以及元气榜API我倒是没想到呢... 多谢了

不过从直播列表获取的房间即使全部监听也仅有50%的舰长覆盖率... 是我的筛选力度还不够吗？
提前感谢...

**Comment by yjqiang** [comment]
> 代码实在有点难读2333 所以想了下还是直接问吧
> 
> 这种堪称恐怖的覆盖率采用的全部是WS弹幕协议监听的吗？感觉这样的话要处理相当大量的数据...
> 不过房间选取的这个API <http://api.live.bilibili.com/room/v1/Area/getListByAreaID?areaId=0&sort=online&pageSize=200&page=1> 以及元气榜API我倒是没想到呢... 多谢了
> 
> 不过从直播列表获取的房间即使全部监听也仅有50%的舰长覆盖率... 是我的筛选力度还不够吗？
> 提前感谢...

tcp  ws的性能消耗过于恐怖    覆盖率是你的问题……

**Comment by Billyzou0741326** [comment]
> tcp ws的性能消耗过于恐怖 覆盖率是你的问题……

NodeJS这边的TCP连接8000房间也仅占几百MB呢 瓶颈已经从资源占用转移到筛选算法了所以想请教一下....
高峰期的覆盖率竟也不高所以觉得应该是监听选择方面的问题

**Comment by yjqiang** [comment]
> > tcp ws的性能消耗过于恐怖 覆盖率是你的问题……
> 
> NodeJS这边的TCP连接8000房间也仅占几百MB呢 瓶颈已经从资源占用转移到筛选算法了所以想请教一下....
> 高峰期的覆盖率竟也不高所以觉得应该是监听选择方面的问题

我有好几套措施的……固定房间加动态房间

**Comment by Billyzou0741326** [comment]
> > > tcp ws的性能消耗过于恐怖 覆盖率是你的问题……
> > 
> > 
> > NodeJS这边的TCP连接8000房间也仅占几百MB呢 瓶颈已经从资源占用转移到筛选算法了所以想请教一下....
> > 高峰期的覆盖率竟也不高所以觉得应该是监听选择方面的问题
> 
> 我有好几套措施的……固定房间加动态房间

动态房间想必是通过直播列表获取的吧
那静态的是取自元气榜和小时榜吗

**Comment by yjqiang** [comment]
> > > > tcp ws的性能消耗过于恐怖 覆盖率是你的问题……
> > > 
> > > 
> > > NodeJS这边的TCP连接8000房间也仅占几百MB呢 瓶颈已经从资源占用转移到筛选算法了所以想请教一下....
> > > 高峰期的覆盖率竟也不高所以觉得应该是监听选择方面的问题
> > 
> > 
> > 我有好几套措施的……固定房间加动态房间
> 
> 动态房间想必是通过直播列表获取的吧
> 那静态的是取自元气榜和小时榜吗

静态是暴力扫描b站的所有房间，动态来源很多有正在直播的有榜单等等

**Comment by Billyzou0741326** [comment]
> 静态是暴力扫描b站的所有房间，动态来源很多有正在直播的有榜单等等

扫描全站这个我没想过hhh果然暴力 
动态来源这个倒是可以完善一下

感谢大佬~
