### ISSUE TITLE
无法发送弹幕，原因未知

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/YjMonitor#14]
登录的账号没有被封禁弹幕，却无法发送弹幕。
![image](https://user-images.githubusercontent.com/42423154/50341126-9e250d00-0558-11e9-9c01-299fea245954.png)

**Comment by rabbit2rabbit** [comment]
![image](https://user-images.githubusercontent.com/42423154/50341228-ff4ce080-0558-11e9-8c08-66f02b5837f9.png)

**Comment by yjqiang** [comment]
你是否更新了最新版

**Comment by rabbit2rabbit** [comment]
2.2.3

**Comment by yjqiang** [comment]
重启之后呢

**Comment by rabbit2rabbit** [comment]
重启两次了，都换过两个账号了，host的弹幕服务器都ping了

**Comment by yjqiang** [comment]
你代码确定没改动？因为这是不可能的事情啊……所有的都会有一个返回json

**Comment by rabbit2rabbit** [comment]
没改动过

**Comment by yjqiang** [comment]
你试试在主项目那里手动6号发送弹幕

**Comment by rabbit2rabbit** [comment]
![image](https://user-images.githubusercontent.com/42423154/50342176-fb22c200-055c-11e9-98a2-4bc8b25fc208.png)

**Comment by yjqiang** [comment]
不是api原因

**Comment by yjqiang** [comment]
> ![image](https://user-images.githubusercontent.com/42423154/50342176-fb22c200-055c-11e9-98a2-4bc8b25fc208.png)
> 

你换一个房间号码设置

**Comment by rabbit2rabbit** [comment]
监控和弹幕控制设置在A房间，现在发送到B房间也同样成功了

**Comment by yjqiang** [comment]
> 监控和弹幕控制设置在A房间，现在发送到B房间也同样成功了

我们之前在共同房间里发现了1-400的账户，就屏蔽了他，不知道是不是你的。建议不要和我们一起混着用

**Comment by yjqiang** [comment]
> 监控和弹幕控制设置在A房间，现在发送到B房间也同样成功了

是不是你的账号……

**Comment by rabbit2rabbit** [comment]
之前1-400的那个是我的，看到房间掉了就补上。
另外被封禁会有返回被封禁的提示，还有“msg repeat的提示”，测试用的账号完全没问题，没被720也没被弹幕封禁

**Comment by yjqiang** [comment]
应该是个bug  但是无从下手

**Comment by rabbit2rabbit** [comment]
是在获取到抽奖id，到尝试发送弹幕前的这个过程，我没看这边的代码，

**Comment by yjqiang** [comment]
现在还能复现么？

**Comment by yjqiang** [comment]
你把代码上面加一些人为print  主体代码在rafflehandler和utils里面，你一看应该就知道了

**Comment by rabbit2rabbit** [comment]
![image](https://user-images.githubusercontent.com/42423154/50343754-185a8f00-0563-11e9-9b6b-aa4091a73957.png)
 出现弹幕6，没有7和8了

**Comment by rabbit2rabbit** [comment]
另外节奏风暴没有用到这个函数
![image](https://user-images.githubusercontent.com/42423154/50343847-81420700-0563-11e9-81ee-0b05dbd2ffb9.png)

**Comment by yjqiang** [comment]
我觉得是网络问题

**Comment by yjqiang** [comment]
我自己跑着看看吧

**Comment by rabbit2rabbit** [comment]
只有第一次尝试用过send(self,msg)函数，之后再获取到id都没有使用到这个函数，连弹幕5都没出现了

**Comment by rabbit2rabbit** [comment]
嗯，你看看吧，我过后几天也没空测试了，加油

**Comment by yjqiang** [comment]
后面5不出现很好理解  queue是堵塞的  前面不执行  后面的也不会运行

**Comment by rabbit2rabbit** [comment]
![image](https://user-images.githubusercontent.com/42423154/50344278-5193fe80-0565-11e9-9912-ce9124a77372.png)
最新的一轮测试，11出现了，后面的if语句一个都没有了
![image](https://user-images.githubusercontent.com/42423154/50344316-79836200-0565-11e9-8567-a2adf5ec7f24.png)

**Comment by yjqiang** [comment]
你把json_response打印出来  11那里

**Comment by rabbit2rabbit** [comment]
![image](https://user-images.githubusercontent.com/42423154/50344740-3d510100-0567-11e9-8df6-8c379d58b222.png)

**Comment by yjqiang** [comment]
> 
> ![image](https://user-images.githubusercontent.com/42423154/50344740-3d510100-0567-11e9-8df6-8c379d58b222.png)
> 

这是哪门子的bug……你试试把账号cookie删除重登  这个bug在2.2.3这里我已经修改了呀……

**Comment by yjqiang** [comment]
你看看我的git history 我上次就是改了这个地方呀……

**Comment by yjqiang** [comment]
你试试过滤之后加一个循环  看看是不是重试可以解决

**Comment by rabbit2rabbit** [comment]
但是我是cookie,csrf等全部清空，只用username,passwd登陆的，没有沿用之前的csrf
你说的循环我不是很理解

**Comment by yjqiang** [comment]
> 但是我是cookie,csrf等全部清空，只用username,passwd登陆的，没有沿用之前的csrf
> 你说的循环我不是很理解

就是有时候b站莫名奇妙认为你过期，但是实际你并没有。这时候重试一次就能通过了

**Comment by rabbit2rabbit** [comment]
用code做验证可以吗？
让我写是真的绞尽脑汁了。。
while code == -111:
	json_response = bilibili.request_send_danmu_msg_web(msg,roomId)
	code_1 = json_response['code']
	if code_1 == 0:
		break
	else:
		time.sleep(0.5)

**Comment by rabbit2rabbit** [comment]
在外面用手机写的，要回去才能做验证，

**Comment by yjqiang** [comment]
> 在外面用手机写的，要回去才能做验证，

如何 还有这个问题么

**Comment by rabbit2rabbit** [comment]
还是没有解决这个问题。
我是把代码放在check_send函数的for i in range(15)下。
手机上传图片到git失败

**Comment by rabbit2rabbit** [comment]
我把服务器发你邮箱了，你看看调试下，问题在哪里

**Comment by yjqiang** [comment]
我试了一下 没看到  这个不是一直复现的吧？是偶尔才会出么

**Comment by rabbit2rabbit** [comment]
凌晨2点我重启服务器了，之后我就没试过了，如果是两点后调试没出问题，或许是网络的原因，2点之前的话是一直都有出现问题，

**Comment by yjqiang** [comment]
> 凌晨2点我重启服务器了，之后我就没试过了，如果是两点后调试没出问题，或许是网络的原因，2点之前的话是一直都有出现问题，

可能是b站问题吧  我测试了没看到问题 这个问题很频繁么  还是看人品1%概率？

**Comment by yjqiang** [comment]
@rabbit2rabbit 你观察一下最近还有么  没有的话基本就是b站调试的bug了

**Comment by yjqiang** [comment]
@rabbit2rabbit ??

**Comment by rabbit2rabbit** [comment]
最近工作较忙，没什么空测试观察。
我过两天有空了，尽快反馈给你，抱歉

**Comment by yjqiang** [comment]
> 最近工作较忙，没什么空测试观察。
> 我过两天有空了，尽快反馈给你，抱歉

enen

**Comment by rabbit2rabbit** [comment]
观察过了，最近没有这个问题 了，或许真是B站问题了
