### ISSUE TITLE
弹幕queue策略实现这里可能出了问题

### ISSUE THREAD

**Issue by pridelove** [yjqiang/YjMonitor#15]
弹幕queue策略实现这里可能出了问题  如图
![tim 20190119183237](https://user-images.githubusercontent.com/38132799/51425571-ba2fd300-1c18-11e9-9226-995d959fa4dc.png)

**Comment by yjqiang** [comment]
稍后再上一个辅助debug的东西吧。

**Comment by yjqiang** [comment]
额，架构完全改了。。。。
