### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by wwh1004** [yjqiang/YjMonitor#18]
user.toml里新添加的用户似乎无法登录，要用bili2.0先登录创建缓存，再把user.toml的内容复制过去才行
![Snipaste_2019-04-04_15-57-48](https://user-images.githubusercontent.com/27536652/55539129-87af5580-56f2-11e9-98a6-3a1f14c7e35a.png)

**Comment by yjqiang** [comment]
> user.toml里新添加的用户似乎无法登录，要用bili2.0先登录创建缓存，再把user.toml的内容复制过去才行
> ![Snipaste_2019-04-04_15-57-48](https://user-images.githubusercontent.com/27536652/55539129-87af5580-56f2-11e9-98a6-3a1f14c7e35a.png)
> 

不会啊。添加用户直接关了脚本自己加就行，可以不带cookie。完了后启动脚本。正常运行。

**Comment by wwh1004** [comment]
直接clone的仓库，user.toml里面直接添加账号密码，然后运行脚本，就是上面那个报错，树莓派上和我pc上运行都是这样
![Snipaste_2019-04-04_16-38-02](https://user-images.githubusercontent.com/27536652/55541678-0955b200-56f8-11e9-811c-5a8a3c2d2e3c.png)

**Comment by yjqiang** [comment]
话说这代码报错感觉不是我的原因吧……这玩意和我代码应该无关

**Comment by wwh1004** [comment]
但是我把带了缓存的复制过去就正常
![Snipaste_2019-04-04_16-39-33](https://user-images.githubusercontent.com/27536652/55541816-58034c00-56f8-11e9-8515-d485f2b910ed.png)
![Snipaste_2019-04-04_16-40-15](https://user-images.githubusercontent.com/27536652/55541820-59cd0f80-56f8-11e9-9aae-efc1a2d0e531.png)

**Comment by yjqiang** [comment]
这俩报错类似。但不一样。我测试过，不会这么出错……你本地网络是不是不好啊……

**Comment by yjqiang** [comment]
嗯……这可能是出了验证码？

**Comment by yjqiang** [comment]
你等一下  我打个补丁

**Comment by yjqiang** [comment]
@wwh1004 你更新一下看看结果

**Comment by wwh1004** [comment]
可以了
