### ISSUE TITLE
延时进入房间

### ISSUE THREAD

**Issue by wwh1004** [yjqiang/YjMonitor#19]
不要所有tcp客户端一起发送连接请求，很容易出现失去连接。

我之前用我没写完的那个c#版本（一直没时间写）测试，一次性全部连接上b站弹幕服务器，最多挂3000个连接，cpu占用也很大。如果启动一个tcp连接之后延时一段时间再启动下一个tcp连接，可以挂至少6000个连接，而且很稳定（不敢再高了，怕b站把我ip封了），cpu占用也很平缓

本来想自己改然后发pr的，但是不会改。。。

下面那个代码的意思是
interval代表多少时间之后启动下一个tcp连接，计算方式是把所有tcp客户端连接平均分配到30秒完成，而不是一起连接到服务器

![Snipaste_2019-05-11_00-08-31](https://user-images.githubusercontent.com/27536652/57541299-3f362800-7381-11e9-8369-9267c29c5b5e.png)

**Comment by yjqiang** [comment]
不打算这样改了  之后只会考虑换语言  因为我觉得python这语言可能到头了  极限应该就是3k 4k房间了

**Comment by yjqiang** [comment]
除非等uvloop否则基本不会有性能飞跃  上次的飞跃是我用tcp替换了ws连接方式

**Comment by yjqiang** [comment]
真香，老弟你也来点吧

**Comment by wwh1004** [comment]
一直刷too many open files是啥情况
![Snipaste_2019-05-25_22-49-20](https://user-images.githubusercontent.com/27536652/58370972-62470700-7f3f-11e9-8313-73d5506fc84b.png)

**Comment by yjqiang** [comment]
可能是linux底层的东西吧

**Comment by yjqiang** [comment]
https://stackoverflow.com/questions/18280612/ioerror-errno-24-too-many-open-files

**Comment by wwh1004** [comment]
关键是没法用，很奇怪，windows下正常，树莓派里面没法用
![Snipaste_2019-05-25_22-57-26](https://user-images.githubusercontent.com/27536652/58371054-835c2780-7f40-11e9-9a2e-044991473c27.png)
树莓派实在卡，没法调试...不清楚是哪里出的问题，不知道能不能改改

**Comment by yjqiang** [comment]
肯定是树莓派性能差，导致限制了

**Comment by wwh1004** [comment]
终于搞定了，unix真的是难折腾，，搞好一次真不想搞第二次...改个limit都那么麻烦
树莓派上也能挂这么多房间，还挺稳定的，确实香
