### ISSUE TITLE
检测舰长不发送弹幕数据

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/YjMonitor#2]
![default](https://user-images.githubusercontent.com/42423154/45733963-3e475f00-bc15-11e8-8b5a-322520b4aa5a.png)
检测到舰长，不发送弹幕，貌似舰长参数有新变化

**Comment by yjqiang** [comment]
最新版已经修复

**Comment by rabbit2rabbit** [comment]
请教个问题：安装依赖包出现这个问题是哪里出错呢？
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-fo85vk
4b\matplotlib\

pip、install、steup、都pip更新了，用PY3.6，是在搞不懂，之前的服务器装起来都没问题

**Comment by yjqiang** [comment]
建议安装anaconda吧 matplotlib安装问题一堆
