### ISSUE TITLE
自建使用疑问

### ISSUE THREAD

**Issue by falcomzwei** [yjqiang/YjMonitor#20]
单开monitor模式
raffle_minitor_roomid用的是不在直播的空房间，弹幕发出，但是舰长未领取。

**Comment by yjqiang** [comment]
bili2.0最新版已经移除了弹幕直播间这个办法  不打算之后支持了

**Comment by falcomzwei** [comment]
还是无法领取_(:з」∠)_
已经更新到目前最新版本
本地开了monitor的run.py和 ws_server的run.py

=============================================

ctrl的配置文件
[other_control]  # 其他细节控制
post_office = 'http://127.0.0.1:8001/post_raffle'

START = 0
END = 200

yjmonitor_tcp_addr = ''
yjmonitor_tcp_key = ''

=============================================
monitor的打印信息
[2019-05-24 22:22:51] check_results:
# <class 'tasks.guard_raffle_handler.GuardRafflJoinTask'>
# [(-2, (0, 0), {'raffle_id': 1127691, 'room_id': 763679, 'raffle_type': 'GUARD', 'end_time': 1558708011})]
raffle_data {'raffle_id': 1127691, 'room_id': 763679, 'raffle_type': 'GUARD', 'end_time': 1558708011} 0
[2019-05-24 22:22:51] 已推送1127691,结果反馈为: {'code': 0, 'type': '', 'data': {}} (用户id:0 名字:)

=============================================
ws_server的打印信息
[2019-05-24 22:22:51] 接收到抽奖{'raffle_id': 1127691, 'room_id': 763679, 'raffle_type': 'GUARD', 'end_time': 1558708011, 'latest_update_rooms_time': 0}
{'code': 0, 'type': 'raffle', 'data': {'raffle_id': 1127691, 'room_id': 763679, 'raffle_type': 'GUARD', 'end_time': 1558708011, 'latest_update_rooms_time': 0}}

=============================================
按room_id进入房间发现未领取，确认手动可领取没有进小黑屋。

**Comment by yjqiang** [comment]
`yjmonitor_tcp_addr` 和 `yjmonitor_tcp_key` 需要填写

**Comment by falcomzwei** [comment]
能说一下分别应该填什么吗？不是很明白

**Comment by yjqiang** [comment]
https://github.com/yjqiang/YjMonitor#ws_client%E9%83%A8%E5%88%86
这里面是控制，需要自己生成一个 key，然后 toml 里面填写上这个 key 以及你的 server 的地址。

**Comment by falcomzwei** [comment]
yjmonitor_tcp_addr填的是127.0.0.1:8001
用req_create_key.py生成的值填入yjmonitor_tcp_key

用req_check.py检查过，返回是
JSON结果: {'code': 0, 'type': 'server_status', 'data': {'version': '0.1.2', 'observers_num': '当前用户共0', 'posters_count': {'0-500V6.0b2': 1558749277}, 'curr_db': '', 'search_results': {'key_searched_by_naive_hash': 'key的有效时间:1558748569-0, 最多允许同时在线人数为1'}, 'curr_time': 1558749296, 'encrypted_msg2admin': [], 'encrypted_msg2super_admin': []}}

还是没法领取，是不是有什么操作漏掉了……

**Comment by yjqiang** [comment]
addr需要填写[tcp://127.0.0.1:8002](https://github.com/yjqiang/bili2.0/blob/master/conf/ctrl.sample.toml#L12)

**Comment by falcomzwei** [comment]
改了之后还是不行_(:з」∠)_

**Comment by yjqiang** [comment]
你把整个控制文件贴上来好不好……

**Comment by falcomzwei** [comment]
[other_control]  # 其他细节控制
post_office = 'http://127.0.0.1:8001/post_raffle'

START = 0
END = 500

yjmonitor_tcp_addr = 'tcp://127.0.0.1:8002'
yjmonitor_tcp_key = '^=`EK]bd.t5a5`98'

**Comment by yjqiang** [comment]
你先不要搞推送，说不定你连server都连不上

**Comment by falcomzwei** [comment]
有跑过run_polling.py
打印
0号数据连接确认建立连接（^=`EK]bd.t5a5`98）


sever打印
IP(   127.0.0.1   )用户9cc52加入

**Comment by yjqiang** [comment]
那肯定就正常了 我这里跑着好几个监控 没有任何问题

**Comment by falcomzwei** [comment]
一会儿我换个设备试试

**Comment by falcomzwei** [comment]
已经可以领了，是我自己网络的问题，感谢！

**Comment by Molly-123** [comment]
你是怎么运行req_create_key.py的，我运行显示
HTTPConnectionPool(host='192.168.0.107', port=8001): Max retries exceeded with url: create_key (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000000F2F42F24A8>, 'Connection to 192.168.0.107 timed out. (connect timeout=3)'))

**Comment by yjqiang** [comment]
> 你是怎么运行req_create_key.py的，我运行显示
> HTTPConnectionPool(host='192.168.0.107', port=8001): Max retries exceeded with url: create_key (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000000F2F42F24A8>, 'Connection to 192.168.0.107 timed out. (connect timeout=3)'))

需要本地运行server才能连接上，server 所在的 ip 以及端口填在 https://github.com/yjqiang/YjMonitor/blob/master/ctrl/global_var.py#L3

**Comment by Molly-123** [comment]
server 里面的run.py运行闪退，我截图看了一下反馈
line 14，in<module>
from argon2 import PasswordHasher
Module NotFoundError：No module named 'argon2'

**Comment by Molly-123** [comment]
server 里面的run.py运行闪退，我截图看了一下反馈
line 14，in<module>
from argon2 import PasswordHasher
Module NotFoundError：No module named 'argon2'

**Comment by Molly-123** [comment]
尝试安装argon2库，失败了

**Comment by yjqiang** [comment]
https://github.com/yjqiang/YjMonitor/blob/master/requirements.txt#L7

**Comment by Molly-123** [comment]
非管理员身份运行时是
======== Running on http://0.0.0.0:8001 ========
(Press CTRL+C to quit)
管理员身份运行结果如下，我没太懂
C:\Windows\system32>C:\Users\ativ\Desktop\YjMonitor-master\server\run.py
Traceback (most recent call last):
  File "C:\Users\ativ\Desktop\YjMonitor-master\server\run.py", line 280, in <mod
ule>
    main()
  File "C:\Users\ativ\Desktop\YjMonitor-master\server\run.py", line 269, in main

    loop.run_until_complete(coro)
  File "E:\python\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "E:\python\lib\asyncio\streams.py", line 114, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "E:\python\lib\asyncio\base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 800
2): 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。

**Comment by Molly-123** [comment]
非管理员身份运行时是
======== Running on http://0.0.0.0:8001 ========
(Press CTRL+C to quit)
管理员身份运行结果也是这个，但是这个地址是无效的

**Comment by yjqiang** [comment]
.....本地地址是127.0.0.1啊。。。。。http://127.0.0.1:8001

**Comment by Molly-123** [comment]
我还没有改控制文件呢

**Comment by Molly-123** [comment]
不懂……
他说Press CTRL+C to quit，但是按下去并没有任何反应

**Comment by yjqiang** [comment]
> 不懂……
> 他说Press CTRL+C to quit，但是按下去并没有任何反应

那就不要用了，这东西细节真不好说。https://github.com/yjqiang/bili2.0/issues/129#issuecomment-490492459 我们自建了一个，一个月 10 块。

**Comment by Molly-123** [comment]
好的，谢谢，我把环境重新搭一次试试，不行就氪金，谢谢你！


> > 不懂……
> > 他说Press CTRL+C to quit，但是按下去并没有任何反应
> 
> 那就不要用了，这东西细节真不好说。[yjqiang/bili2.0#129 (comment)](https://github.com/yjqiang/bili2.0/issues/129#issuecomment-490492459) 我们自建了一个，一个月 10 块。

好的，谢谢，我把环境重新搭一次试试，不行就氪金，谢谢你！

**Comment by KNulL0** [comment]
想用两个服务器监控房间，第二个服务器monitor启动的时候一直重复启动数据连接是怎么回事

**Comment by yjqiang** [comment]
> 想用两个服务器监控房间，第二个服务器monitor启动的时候一直重复启动数据连接是怎么回事

你是运行了哪个文件？具体日志如何

**Comment by KNulL0** [comment]
> > 想用两个服务器监控房间，第二个服务器监测启动的时候一直重复启动数据连接是怎么回事
> 
> 你是运行了哪个文件？具体日志如何

/monitor/run.py
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-08-23 22:30:16] http://room.lc4t.cn:8000/dyn_rooms/0-1350
[2019-09-24 12:58:37] https://api.live.bilibili.com/lottery/v1/Lottery/check_guard?roomid=5279
[2019-09-24 12:58:42] https://api.live.bilibili.com/lottery/v1/Lottery/check_guard?roomid=5279

**Comment by KNulL0** [comment]
> > 想用两个服务器监控房间，第二个服务器monitor启动的时候一直重复启动数据连接是怎么回事
> 
> 你是运行了哪个文件？具体日志如何

monitor/run.py     也没报错就是一直重复显示正在启动xxx号数据链接，不提示进入房间
