### ISSUE TITLE
问一下签名的问题

### ISSUE THREAD

**Issue by lovezm** [yjqiang/YjMonitor#24]
创建key以后 链接上了  tcp_client测试也链接了 
但是收不到推送（没有0号数据库的推送）
测试一下 发现签名错误 想问一下这个签名 是用ctrl里面的create_key创建的两个文件吗

**Comment by yjqiang** [comment]
对  创建两对儿

**Comment by yjqiang** [comment]
一对是管理权限，一对是超管权限。管理权限用于推送等功能

**Comment by lovezm** [comment]
需要重命名吗 我发现我放到server的key里面 不推送 233

**Comment by yjqiang** [comment]
当然

**Comment by lovezm** [comment]
好了=。= 感谢
