### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by slinar** [yjqiang/YjMonitor#26]
如题，但是好像没有影响，python3.7.5
![Snipaste_2019-11-12_21-55-11](https://user-images.githubusercontent.com/41759351/68678010-11cc7000-0598-11ea-9b3d-c01db34b44fa.png)

**Comment by yjqiang** [comment]
b站脑瘫测试？cmd没有那就是测试或者新型弹幕了

**Comment by yjqiang** [comment]
{'scene_key': '4', 'scene_value': '423227', 'msg': {'roomid': 423227, 'msg_common': '<%十二少爷V%>在本房间开通了舰长', 'msg_self': '<%十二少爷V%>在本房间开通了舰长', 'link_url': 'http://live.bilibili.com/423227?live_lottery_type=2&broadcast_type=', 'msg_type': 3, 'full': {'head_icon': 'http://i0.hdslb.com/bfs/live/72337e86020b8d0874d817f15c48a610894b94ff.png', 'tail_icon': 'http://i0.hdslb.com/bfs/live/822da481fdaba986d738db5d8fd469ffa95a8fa1.webp', 'head_icon_fa': 'http://i0.hdslb.com/bfs/live/72337e86020b8d0874d817f15c48a610894b94ff.png', 'tail_icon_fa': 'http://i0.hdslb.com/bfs/live/38cb2a9f1209b16c0f15162b0b553e3b28d9f16f.png', 'head_icon_fan': 1, 'tail_icon_fan': 4, 'background': '#FFB03CFF', 'color': '#FFFFFFFF', 'highlight': '#B25AC1FF', 'time': 10}, 'half': {'head_icon': '', 'tail_icon': '', 'background': '', 'color': '', 'highlight': '', 'time': 0}, 'side': {'head_icon': 'http://i0.hdslb.com/bfs/live/31566d8cd5d468c30de8c148c5d06b3b345d8333.png', 'background': '#FFE9C8FF', 'color': '#EF903AFF', 'highlight': '#D54900FF', 'border': '#FFCFA4FF'}, 'shield_uid': 0, 'real_roomid': 423227, 'cmd': 'NOTICE_MSG'}, 'from_id': 423227}

**Comment by yjqiang** [comment]
脑瘫b站

**Comment by slinar** [comment]
这个json的数据结构 emmmmm...

**Comment by slinar** [comment]
其他api还是能收到舰队的抽奖 可以判断下data里有没有cmd 没有的话直接跳过 ?

**Comment by Billyzou0741326** [comment]
那个scene key当时我看到愣了好久23333
跟原来的格式完全不兼容啊

**Comment by Billyzou0741326** [comment]
其实直接取`msg`部分就可以当作舰长消息来处理了好像

**Comment by pjy612** [comment]
这是多了一层吗？看来要加判断了...
