### ISSUE TITLE
内容非法提示

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/YjMonitor#3]
![default](https://user-images.githubusercontent.com/42423154/45846530-9045cd00-bd5a-11e8-9989-da46831291f2.png)
是否因为发送速度过快，连着发两次弹幕中间sleep1秒或许可以解决。

另外，好像看过一次一个房间同时两个舰长出现的时候只发送了一条弹幕，那样是否只识别到这个房间只有一个舰长？

**Comment by yjqiang** [comment]
已经sleep了utils里面有弹幕发送函数

**Comment by yjqiang** [comment]
非法提示这里真的是醉了 我觉得b站是真的sb

**Comment by rabbit2rabbit** [comment]
JJ是非法的关键词……

**Comment by yjqiang** [comment]
神经病……
