### ISSUE TITLE
argon2安装和 key 生成疑问

### ISSUE THREAD

**Issue by Jutean** [yjqiang/YjMonitor#30]
生成钥匙那里不太懂
安装argon2 版本太高
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by Jutean** [comment]
如果行的话我可以贡献我的服务器一起监控

**Comment by yjqiang** [comment]
warning没啥用  argon2版本没问题吧  我尝试过的

**Comment by Jutean** [comment]
但运行报错一直提示要安装这个

**Comment by yjqiang** [comment]
argon2 是 https://pypi.org/project/argon2-cffi/

**Comment by yjqiang** [comment]
你贴全了……  warning没用的

**Comment by Jutean** [comment]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\1\\pip-install-25ffffu8\\argon2\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\1\\pip-install-25ffffu8\\argon2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\1\pip-record-l4akua4g\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Administrator\AppData\Local\Temp\1\pip-install-25ffffu8\argon2\
    Complete output (11 lines):
    Warning: 'classifiers' should be a list, got type 'tuple'
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    copying argon2.py -> build\lib.win-amd64-3.8
    package init file 'phc-winner-argon2\__init__.py' not found (or not a regular file)
    running build_ext
    building '_argon2' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\administrator\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\1\\pip-install-25ffffu8\\argon2\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\1\\pip-install-25ffffu8\\argon2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\1\pip-record-l4akua4g\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by yjqiang** [comment]
……自己百度  需要编译。以及务必确认安装的是 https://pypi.org/project/argon2-cffi/   装错包程序没法跑

**Comment by Jutean** [comment]
pip install argon2-cffi 原来是指令，一直用pip3 install argon2

那再问一下生成key
在YjMonitor-master\ctrl\key生成
只有privkey.pem和pubkey.pem

**Comment by yjqiang** [comment]
手动改名……

**Comment by Jutean** [comment]
# <class 'tasks.pk_raffle_handler.PkRaffleJoinTask'>
# [(-2, (0, 0), {'raffle_id': 633888, 'room_id': 2785651, 'raffle_type': 'PK', 'end_time': 1576631472})]
raffle_data {'raffle_id': 633888, 'room_id': 2785651, 'raffle_type': 'PK', 'end_time': 1576631472} 0
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host 127.0.0.1:8001 ssl:default [远程计算机拒绝网络连接。] http://127.0.0.1:8001/post_raffle
这端口能改吗？应该是和我steam302反代理冲突了。

**Comment by yjqiang** [comment]
你要不把问题分类吧  以及这个东西很复杂……  你搞不好真的不建议问了  细节很多  这个是我自己使用的  我自己维护都很琐碎

**Comment by Jutean** [comment]
233333 好吧
