### ISSUE TITLE
关于Linux不能超过1024个监控房间的问题

### ISSUE THREAD

**Issue by yuban10703** [yjqiang/YjMonitor#34]
https://www.cnblogs.com/royfans/p/10905461.html
把这个改大就好了..........

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/74293982-7655c180-4d77-11ea-9918-f9e42b59fa20.png)

**Comment by yjqiang** [comment]
https://github.com/yjqiang/YjMonitor/issues/33
🆗
