### ISSUE TITLE
关于分布式服务的问题

### ISSUE THREAD

**Issue by yuban10703** [yjqiang/YjMonitor#35]
![image](https://user-images.githubusercontent.com/39484884/76106555-123eba00-6012-11ea-9191-2797cf7ba338.png)
想问一下我这个使用方式是否正确
所有的机子都在一个内网里
![{(@8`G)XZ`IQJ ZK9R95~BM](https://user-images.githubusercontent.com/39484884/76108376-68f9c300-6015-11ea-9042-9e544a5352f7.png)

![image](https://user-images.githubusercontent.com/39484884/76108427-8a5aaf00-6015-11ea-8d72-d69c9022128c.png)
![JWM}M{05T D4Y~R31@S{LMO](https://user-images.githubusercontent.com/39484884/76108756-208ed500-6016-11ea-91cb-19d5b60eac8e.png)
![image](https://user-images.githubusercontent.com/39484884/76108828-46b47500-6016-11ea-9ed8-b6e259177812.png)
这个server的结果很奇怪......

**Comment by yjqiang** [comment]
这就是正常了

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/76128431-48466300-603f-11ea-9cba-2cac9a5c961c.png)
所以还是这个效果最好么
emmmm

**Comment by yjqiang** [comment]
4000房间是1M带宽来说的

**Comment by yuban10703** [comment]
房间开多了,断网重连会卡很久,CPU负载也很高
emmm

**Comment by yjqiang** [comment]
看你带宽以及网络稳定性

**Comment by yjqiang** [comment]
带宽低了房间挂不住

**Comment by yuban10703** [comment]
emmmm

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/76129253-e3d8d300-6041-11ea-8c8d-105120dcf818.png)
这个监控好暴力

**Comment by yuban10703** [comment]
好像没什么问题了,我close了............ :octocat:

**Comment by shoucandanghehe** [comment]
我大概明白怎么用了...
4000房间应该是普通路由的极限了吧
我这里再高就挂不上去了
不过轮询式倒是可以稳定挂8k
看了下连接数
分布式是一直在连接
轮询是平时连接数很少，每10秒左右突然爆炸连接大概160→8600这样
然后连接挂个几秒又都关闭

**Comment by yuban10703** [comment]
> 我大概明白怎么用了...
> 4000房间应该是普通路由的极限了吧
> 我这里再高就挂不上去了
> 不过轮询式倒是可以稳定挂8k
> 看了下连接数
> 分布式是一直在连接
> 轮询是平时连接数很少，每10秒左右突然爆炸连接大概160→8600这样
> 然后连接挂个几秒又都关闭

emmm没整明白

**Comment by shoucandanghehe** [comment]
指同时进行的tcp连接数（ESTABLISHED）
```
netstat -n | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}'
```
每2s输出一次
轮询式我这里的结果类似这样
```
168
169
167
167
168
3657
7324
8712
8756
5246
3487
864
854
853
853
269
168
```
分布式就变成
```
3968
3967
3969
3969
3968
3968
3968
3968
3968
3970
3971
3969
```

**Comment by shoucandanghehe** [comment]
不过我怀疑我家路由器被我玩炸了233
ddns已经ping不通了

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/78238260-f5ad7900-750e-11ea-9c7d-93507e651df3.png)
一般就这个连接数,emm

**Comment by shoucandanghehe** [comment]
那也可能我路由垃圾？
正打算搞个d525做软路由呢

**Comment by yuban10703** [comment]
> 那也可能我路由垃圾？
> 正打算搞个d525做软路由呢

母鸡

**Comment by shoucandanghehe** [comment]
嘛，总之我也没搞太明白，希望yj大佬考研顺利然后赶紧把flag填了（bushi）
