### ISSUE TITLE
搭建方面一些问题

### ISSUE THREAD

**Issue by shoucandanghehe** [yjqiang/YjMonitor#36]
1.同时使用多个子监控的配置文件是
START = 0
END = 4000
START = 0
END = 4000
还是
START = 0
END = 4000
START = 4001
END = 8000
2.分布式服务是只需要填好IP运行server部分还是运行https://github.com/yjqiang/bili_utils/blob/master/fetch_roomids/refresh_rooms_hub/run_distributed.py
还是都要运行？
配置方面又要怎么写
3.暴力轮询部分运行之后无输出该怎么解决？
4.这个要怎么填？tcp://ip:端口？端口默认是啥，配置文件里没找到
yjmonitor_tcp_addr = ''

**Comment by yjqiang** [comment]
1.
START = 0
END = 4000
START = 4000
END = 8000
范围是左闭右开区间
2. 分布式比较繁琐，server要运行，client也需要
3. 暴力轮询正常，不是每次都有结果的
4. 这个是去重的一部分，用在暴力轮询这里，就是你自己监控服务器的地址。其他子监控的结果反馈到了暴力轮询，这样就不再重复推送了。

**Comment by shoucandanghehe** [comment]
4.也就是在一台机子上跑填tcp://127.0.0.1:8001就行是吗
2.分布式配置的具体步骤能麻烦说一下吗，实在是搞不太懂，以及使用的端口自定义都要修改那些地方？

**Comment by yjqiang** [comment]
4.对
2.不要尝试分布式了，我都是每次看代码给说明的。现在没时间仔细看了，挺复杂的一套东西。只能说分布式机制是server负责获取房间，然后根据server的配置文件向各个client推送这些房间。具体你得自己摸索

**Comment by shoucandanghehe** [comment]
好的，谢谢大佬解答，我自己摸索下，不行就不用分布了
