### ISSUE TITLE
在一台机子上直接开两个子监控不使用分布式可以吗？

### ISSUE THREAD

**Issue by shoucandanghehe** [yjqiang/YjMonitor#37]
配置文件这样写
START = 0
END = 15000
START = 15000
END = 30000
突然开了个脑洞233
如果可以的话暴力轮询又需要怎么设置

**Comment by yjqiang** [comment]
你完全可以试试看  直接炸掉

**Comment by shoucandanghehe** [comment]
233
那知道了
