### ISSUE TITLE
监控房间选取

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/YjMonitor#4]
监控逻辑还是有点漏洞的，例如设定的获取排名1-500热度房间，且重新获取的时间为半个小时，如果刚好有个房间在这16分刚开播（热度为零），然后到45分之前开通了100个舰长，舰长时间只有二十分钟，这样就会检测不到这期间的100个舰长抽奖。
先把问题提出来，之后看有没有想法或者办法能弥补这个漏洞

**Comment by yjqiang** [comment]
不可能完全弥补的 没有办法 只有缓和

**Comment by rabbit2rabbit** [comment]
就是有个比较笨的思路，就是这1-500个房间再增加一个监控，刷新时间为30分和00分，进入房间是检测当前房间有没有可参与的舰长抽奖，而且重复raffleid也可以自动忽略不参与，还算可以。
只不过这个方法太浪费资源了，需要多增加一倍的机器。痛脚

**Comment by yjqiang** [comment]
或者找b站新开房间的api  记得有  然后专门一个人去监控

**Comment by rabbit2rabbit** [comment]
想法：一个账号关注全部开通了直播间的账号，或许可以通过抓APP端的开播提示来达到知道哪个房间开播的API。

**Comment by yjqiang** [comment]
梦游呢。。。一共十万多房间

**Comment by yjqiang** [comment]
现在的默认房间是不足补3号 然后静默监控  打算  默认房间补足按照关注度排序的房间   当然会去重 这样如何

**Comment by rabbit2rabbit** [comment]
去重之外，加上检查当前房间有没有历史弹幕，防止主站的知名认证up也开通了直播间而不直播的尴尬

**Comment by yjqiang** [comment]
历史弹幕多久清除？

**Comment by yjqiang** [comment]
还是永远存在

**Comment by rabbit2rabbit** [comment]
大约24小时，超过一天没弹幕再次进入房间会没有弹幕

**Comment by yjqiang** [comment]
那这个判别可不行

**Comment by yjqiang** [comment]
我几天前抓了1万直播间  按照关注度排了顺序

**Comment by yjqiang** [comment]
不对  抓了全部直播间  按照关注取了前10k

**Comment by rabbit2rabbit** [comment]
只看粉丝关注这个指标实际上有点不太可取，毕竟关注可以作假的，而且关注的排名基本上不会有太大的变化了，可以直接写一个固定的list了。排名靠前的都是百万、几十万的差距，到了几万的关注才多了起来

**Comment by yjqiang** [comment]
我觉得关注度可以了，唯一要判定的就是是否开播，这个很难，暂时不判定了。关注度基本就是热度

**Comment by yjqiang** [comment]
打算用房间粉丝投喂7天榜  基本上不足10人的都是不直播的  直播过的主播基本都有投喂10人排名的
