### ISSUE TITLE
monitor 登不上账号了

### ISSUE THREAD

**Issue by KNulL0** [yjqiang/YjMonitor#41]
用bili2.0先登录后把cookie复制过去，但是显示token失效

**Comment by shoucandanghehe** [comment]
https://github.com/yjqiang/bili2.0/issues/306
里面的解决办法应该监控也能用

**Comment by KNulL0** [comment]
> [yjqiang / bili2.0＃306](https://github.com/yjqiang/bili2.0/issues/306)
> 内部的解决方法应该监控也能用

没有用啊

**Comment by KNulL0** [comment]
账号一登陆就会异常。。。

**Comment by yjqiang** [comment]
minitor其实可以不需要登陆的。当时我为了统一才这样的 https://github.com/yjqiang/YjMonitor/blob/master/monitor/run.py#L41
这一行注释掉，就不用登陆了，其他的监控客户端也类似
