### ISSUE TITLE
没有区分msg in 1s的非法检测

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/YjMonitor#5]
![image](https://user-images.githubusercontent.com/42423154/47259169-6a862200-d4d8-11e8-9358-c2c08eb6904c.png)
测试弹幕应该是没有非法检测词，是msg in 1s

**Comment by yjqiang** [comment]
这部分逻辑没问题 这是两次的报错

**Comment by yjqiang** [comment]
b站对p4这个关键词 无论间隔什么  都屏蔽……我觉得b站应该脑子进水了

**Comment by yjqiang** [comment]
均已经处理以上问题
