### ISSUE TITLE
近期非法反馈的频率越来越高

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/YjMonitor#8]
![b d e bpbrlm 1 pdw9 fun](https://user-images.githubusercontent.com/42423154/47992745-a6e88d80-e128-11e8-98aa-2f6019689e9f.png)
![a4uf6 t 7p6m 6lj2u9tq 3](https://user-images.githubusercontent.com/42423154/47992750-a94ae780-e128-11e8-9f8a-f5b13814f602.png)
![qh k xwa5o vck _036t](https://user-images.githubusercontent.com/42423154/47992754-ac45d800-e128-11e8-9c88-b5e082f83b0b.png)
这些都是随手截的，估计没看到的有很多

**Comment by rabbit2rabbit** [comment]
经测试，是特殊符号后面不能加数字，具体哪些符号没全部测试统计，至少+和~是后面不能加数字，即使和数字中间有中文字符

**Comment by rabbit2rabbit** [comment]
数字5、6、8没有被屏蔽，还可以使用，主要是一些数字和符号链接的弹幕被屏蔽了

**Comment by yjqiang** [comment]
打算后期直接用原10进制处理，否则已有的一些加上字母数字组合，会导致碰到屏蔽关键词几率大幅上升

**Comment by yjqiang** [comment]
你觉得呢 怎么有效处理关键词屏蔽呢？

**Comment by yjqiang** [comment]
还要考虑弹幕字数限制，唉

**Comment by rabbit2rabbit** [comment]
id用百家姓建立字典（元祖、列表），每2个数字切片，切片的两位数为索引值，对应汉字，发送。解密则用汉字在字典中取value。

roomid较短，可用小写组成的10进制写密文，（abcdefghij）。
即使是风暴id12位加密后成6个字符，加间断符号，加10位长号房间密文，也最多17个字符

这是我的理论想法，不知道是否可行

**Comment by yjqiang** [comment]
百家姓说不定更是一堆关键词……

**Comment by yjqiang** [comment]
目前已经着手做了原文10进制发送、弹幕切割（割成两份）以及对应的弹幕粘合。感觉这样会好一点。你觉得呢
