### ISSUE TITLE
弹幕发送频繁提示

### ISSUE THREAD

**Issue by Pakne** [yjqiang/YjMonitor#9]
[2018-11-09 21:18:30] 95号弹幕监控进入房间（3624449）
[2018-11-09 21:18:30] 93号弹幕监控进入房间（10658142）
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
[2018-11-09 21:18:51] 1号弹幕监控心跳
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
当前时间为 21:18:55
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
[2018-11-09 21:19:21] 1号弹幕监控心跳
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
当前时间为 21:19:25
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
[2018-11-09 21:19:33] 弹幕发送频繁提示
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'msg repeat', 'data': []} 242.10943409~7
{'code': 0, 'msg': 'fire', 'data': []} 242.10943409~7

**Comment by yjqiang** [comment]
fixed
